# Generated by Django 4.1 on 2024-05-17 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meal",
            fields=[
                ("food_name", models.CharField(max_length=100, verbose_name="食事内容")),
                ("calories", models.IntegerField(verbose_name="カロリー")),
                ("date", models.DateField(verbose_name="日付")),
                ("eaten_at", models.DateTimeField(verbose_name="摂取時間")),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "朝食"),
                            ("lunch", "昼食"),
                            ("dinner", "夕食"),
                        ],
                        max_length=10,
                        verbose_name="食事の種類",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "食事",
                "verbose_name_plural": "食事",
                "ordering": ["-date", "-eaten_at"],
            },
        ),
        migrations.CreateModel(
            name="TotalCalories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.PositiveIntegerField(default=0, verbose_name="年齢")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "男性"), ("F", "女性")],
                        max_length=1,
                        verbose_name="性別",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RelatedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("additional_info", models.CharField(max_length=255)),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_data",
                        to="accounts.meal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="食事内容")),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.meal",
                        verbose_name="食事",
                    ),
                ),
            ],
        ),
    ]
