# Generated by Django 4.2.13 on 2024-06-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="eaten_at",
            field=models.TimeField(verbose_name="摂取時間"),
        ),
    ]
